// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: answers.sql

package db

import (
	"context"
)

const createAnswer = `-- name: CreateAnswer :one
INSERT INTO answers (id, question_id, text, is_correct)
VALUES ($1, $2, $3, $4)
RETURNING id, question_id, text, is_correct
`

type CreateAnswerParams struct {
	ID         string `json:"id"`
	QuestionID string `json:"question_id"`
	Text       string `json:"text"`
	IsCorrect  bool   `json:"is_correct"`
}

func (q *Queries) CreateAnswer(ctx context.Context, arg CreateAnswerParams) (Answer, error) {
	row := q.db.QueryRow(ctx, createAnswer,
		arg.ID,
		arg.QuestionID,
		arg.Text,
		arg.IsCorrect,
	)
	var i Answer
	err := row.Scan(
		&i.ID,
		&i.QuestionID,
		&i.Text,
		&i.IsCorrect,
	)
	return i, err
}

const deleteAnswer = `-- name: DeleteAnswer :exec
DELETE FROM answers WHERE id = $1
`

func (q *Queries) DeleteAnswer(ctx context.Context, id string) error {
	_, err := q.db.Exec(ctx, deleteAnswer, id)
	return err
}

const deleteAnswersByQuestionID = `-- name: DeleteAnswersByQuestionID :exec
DELETE FROM answers WHERE question_id = $1
`

func (q *Queries) DeleteAnswersByQuestionID(ctx context.Context, questionID string) error {
	_, err := q.db.Exec(ctx, deleteAnswersByQuestionID, questionID)
	return err
}

const getAnswersByQuestionID = `-- name: GetAnswersByQuestionID :many
SELECT id, question_id, text, is_correct FROM answers WHERE question_id = $1
`

func (q *Queries) GetAnswersByQuestionID(ctx context.Context, questionID string) ([]Answer, error) {
	rows, err := q.db.Query(ctx, getAnswersByQuestionID, questionID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Answer{}
	for rows.Next() {
		var i Answer
		if err := rows.Scan(
			&i.ID,
			&i.QuestionID,
			&i.Text,
			&i.IsCorrect,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateAnswer = `-- name: UpdateAnswer :one
UPDATE answers SET text = $2, is_correct = $3 WHERE id = $1 RETURNING id, question_id, text, is_correct
`

type UpdateAnswerParams struct {
	ID        string `json:"id"`
	Text      string `json:"text"`
	IsCorrect bool   `json:"is_correct"`
}

func (q *Queries) UpdateAnswer(ctx context.Context, arg UpdateAnswerParams) (Answer, error) {
	row := q.db.QueryRow(ctx, updateAnswer, arg.ID, arg.Text, arg.IsCorrect)
	var i Answer
	err := row.Scan(
		&i.ID,
		&i.QuestionID,
		&i.Text,
		&i.IsCorrect,
	)
	return i, err
}
