// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package db

import (
	"database/sql/driver"
	"fmt"

	"github.com/jackc/pgx/v5/pgtype"
)

type QuestionType string

const (
	QuestionTypeSINGLE   QuestionType = "SINGLE"
	QuestionTypeMULTIPLE QuestionType = "MULTIPLE"
)

func (e *QuestionType) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = QuestionType(s)
	case string:
		*e = QuestionType(s)
	default:
		return fmt.Errorf("unsupported scan type for QuestionType: %T", src)
	}
	return nil
}

type NullQuestionType struct {
	QuestionType QuestionType `json:"question_type"`
	Valid        bool         `json:"valid"` // Valid is true if QuestionType is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullQuestionType) Scan(value interface{}) error {
	if value == nil {
		ns.QuestionType, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.QuestionType.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullQuestionType) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.QuestionType), nil
}

func (e QuestionType) Valid() bool {
	switch e {
	case QuestionTypeSINGLE,
		QuestionTypeMULTIPLE:
		return true
	}
	return false
}

type Role string

const (
	RoleORGANIZER   Role = "ORGANIZER"
	RolePARTICIPANT Role = "PARTICIPANT"
)

func (e *Role) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = Role(s)
	case string:
		*e = Role(s)
	default:
		return fmt.Errorf("unsupported scan type for Role: %T", src)
	}
	return nil
}

type NullRole struct {
	Role  Role `json:"role"`
	Valid bool `json:"valid"` // Valid is true if Role is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullRole) Scan(value interface{}) error {
	if value == nil {
		ns.Role, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.Role.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullRole) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.Role), nil
}

func (e Role) Valid() bool {
	switch e {
	case RoleORGANIZER,
		RolePARTICIPANT:
		return true
	}
	return false
}

type SessionStatus string

const (
	SessionStatusWAITING  SessionStatus = "WAITING"
	SessionStatusACTIVE   SessionStatus = "ACTIVE"
	SessionStatusFINISHED SessionStatus = "FINISHED"
)

func (e *SessionStatus) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = SessionStatus(s)
	case string:
		*e = SessionStatus(s)
	default:
		return fmt.Errorf("unsupported scan type for SessionStatus: %T", src)
	}
	return nil
}

type NullSessionStatus struct {
	SessionStatus SessionStatus `json:"session_status"`
	Valid         bool          `json:"valid"` // Valid is true if SessionStatus is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullSessionStatus) Scan(value interface{}) error {
	if value == nil {
		ns.SessionStatus, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.SessionStatus.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullSessionStatus) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.SessionStatus), nil
}

func (e SessionStatus) Valid() bool {
	switch e {
	case SessionStatusWAITING,
		SessionStatusACTIVE,
		SessionStatusFINISHED:
		return true
	}
	return false
}

type Answer struct {
	ID         string `json:"id"`
	QuestionID string `json:"question_id"`
	Text       string `json:"text"`
	IsCorrect  bool   `json:"is_correct"`
}

type PasswordResetToken struct {
	ID        string             `json:"id"`
	Email     string             `json:"email"`
	Token     string             `json:"token"`
	ExpiresAt pgtype.Timestamptz `json:"expires_at"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
}

type PlayerAnswer struct {
	ID              string             `json:"id"`
	SessionPlayerID string             `json:"session_player_id"`
	QuestionID      string             `json:"question_id"`
	AnsweredAt      pgtype.Timestamptz `json:"answered_at"`
	IsCorrect       bool               `json:"is_correct"`
	Points          int32              `json:"points"`
}

type PlayerAnswerAnswer struct {
	PlayerAnswerID string `json:"player_answer_id"`
	AnswerID       string `json:"answer_id"`
}

type Question struct {
	ID        string       `json:"id"`
	QuizID    string       `json:"quiz_id"`
	Text      string       `json:"text"`
	ImageUrl  *string      `json:"image_url"`
	Type      QuestionType `json:"type"`
	Order     int32        `json:"order"`
	Tags      []string     `json:"tags"`
	TimeLimit int32        `json:"time_limit"`
	Points    int32        `json:"points"`
}

type Quiz struct {
	ID                string             `json:"id"`
	Title             string             `json:"title"`
	Description       string             `json:"description"`
	Category          string             `json:"category"`
	TimePerQuestion   int32              `json:"time_per_question"`
	PointsPerQuestion int32              `json:"points_per_question"`
	Scoring           string             `json:"scoring"`
	Difficulty        string             `json:"difficulty"`
	Tags              []string           `json:"tags"`
	CoverImageUrl     *string            `json:"cover_image_url"`
	Archived          bool               `json:"archived"`
	AuthorID          string             `json:"author_id"`
	CreatedAt         pgtype.Timestamptz `json:"created_at"`
}

type QuizSession struct {
	ID        string             `json:"id"`
	QuizID    string             `json:"quiz_id"`
	RoomCode  string             `json:"room_code"`
	Status    SessionStatus      `json:"status"`
	StartedAt pgtype.Timestamptz `json:"started_at"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
}

type SessionPlayer struct {
	ID        string             `json:"id"`
	SessionID string             `json:"session_id"`
	UserID    string             `json:"user_id"`
	Score     int32              `json:"score"`
	JoinedAt  pgtype.Timestamptz `json:"joined_at"`
}

type User struct {
	ID        string             `json:"id"`
	Email     string             `json:"email"`
	Password  *string            `json:"password"`
	Name      string             `json:"name"`
	Role      Role               `json:"role"`
	GoogleID  *string            `json:"google_id"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
}
