// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: password_reset.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createPasswordResetToken = `-- name: CreatePasswordResetToken :one
INSERT INTO password_reset_tokens (id, email, token, expires_at, created_at)
VALUES ($1, $2, $3, $4, NOW())
RETURNING id, email, token, expires_at, created_at
`

type CreatePasswordResetTokenParams struct {
	ID        string             `json:"id"`
	Email     string             `json:"email"`
	Token     string             `json:"token"`
	ExpiresAt pgtype.Timestamptz `json:"expires_at"`
}

func (q *Queries) CreatePasswordResetToken(ctx context.Context, arg CreatePasswordResetTokenParams) (PasswordResetToken, error) {
	row := q.db.QueryRow(ctx, createPasswordResetToken,
		arg.ID,
		arg.Email,
		arg.Token,
		arg.ExpiresAt,
	)
	var i PasswordResetToken
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.Token,
		&i.ExpiresAt,
		&i.CreatedAt,
	)
	return i, err
}

const deletePasswordResetToken = `-- name: DeletePasswordResetToken :exec
DELETE FROM password_reset_tokens WHERE token = $1
`

func (q *Queries) DeletePasswordResetToken(ctx context.Context, token string) error {
	_, err := q.db.Exec(ctx, deletePasswordResetToken, token)
	return err
}

const deletePasswordResetTokensByEmail = `-- name: DeletePasswordResetTokensByEmail :exec
DELETE FROM password_reset_tokens WHERE email = $1
`

func (q *Queries) DeletePasswordResetTokensByEmail(ctx context.Context, email string) error {
	_, err := q.db.Exec(ctx, deletePasswordResetTokensByEmail, email)
	return err
}

const getPasswordResetToken = `-- name: GetPasswordResetToken :one
SELECT id, email, token, expires_at, created_at FROM password_reset_tokens WHERE token = $1
`

func (q *Queries) GetPasswordResetToken(ctx context.Context, token string) (PasswordResetToken, error) {
	row := q.db.QueryRow(ctx, getPasswordResetToken, token)
	var i PasswordResetToken
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.Token,
		&i.ExpiresAt,
		&i.CreatedAt,
	)
	return i, err
}
