// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: player_answers.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const connectPlayerAnswerToAnswer = `-- name: ConnectPlayerAnswerToAnswer :exec
INSERT INTO player_answer_answers (player_answer_id, answer_id)
VALUES ($1, $2)
ON CONFLICT DO NOTHING
`

type ConnectPlayerAnswerToAnswerParams struct {
	PlayerAnswerID string `json:"player_answer_id"`
	AnswerID       string `json:"answer_id"`
}

func (q *Queries) ConnectPlayerAnswerToAnswer(ctx context.Context, arg ConnectPlayerAnswerToAnswerParams) error {
	_, err := q.db.Exec(ctx, connectPlayerAnswerToAnswer, arg.PlayerAnswerID, arg.AnswerID)
	return err
}

const countAnsweredPlayers = `-- name: CountAnsweredPlayers :one
SELECT COUNT(*) FROM player_answers pa
JOIN session_players sp ON sp.id = pa.session_player_id
WHERE pa.question_id = $1 AND sp.session_id = $2
`

type CountAnsweredPlayersParams struct {
	QuestionID string `json:"question_id"`
	SessionID  string `json:"session_id"`
}

func (q *Queries) CountAnsweredPlayers(ctx context.Context, arg CountAnsweredPlayersParams) (int64, error) {
	row := q.db.QueryRow(ctx, countAnsweredPlayers, arg.QuestionID, arg.SessionID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createPlayerAnswer = `-- name: CreatePlayerAnswer :one
INSERT INTO player_answers (id, session_player_id, question_id, answered_at, is_correct, points)
VALUES ($1, $2, $3, NOW(), $4, $5)
RETURNING id, session_player_id, question_id, answered_at, is_correct, points
`

type CreatePlayerAnswerParams struct {
	ID              string `json:"id"`
	SessionPlayerID string `json:"session_player_id"`
	QuestionID      string `json:"question_id"`
	IsCorrect       bool   `json:"is_correct"`
	Points          int32  `json:"points"`
}

func (q *Queries) CreatePlayerAnswer(ctx context.Context, arg CreatePlayerAnswerParams) (PlayerAnswer, error) {
	row := q.db.QueryRow(ctx, createPlayerAnswer,
		arg.ID,
		arg.SessionPlayerID,
		arg.QuestionID,
		arg.IsCorrect,
		arg.Points,
	)
	var i PlayerAnswer
	err := row.Scan(
		&i.ID,
		&i.SessionPlayerID,
		&i.QuestionID,
		&i.AnsweredAt,
		&i.IsCorrect,
		&i.Points,
	)
	return i, err
}

const getPlayerAnswerBySessionPlayerAndQuestion = `-- name: GetPlayerAnswerBySessionPlayerAndQuestion :one
SELECT id, session_player_id, question_id, answered_at, is_correct, points FROM player_answers
WHERE session_player_id = $1 AND question_id = $2
`

type GetPlayerAnswerBySessionPlayerAndQuestionParams struct {
	SessionPlayerID string `json:"session_player_id"`
	QuestionID      string `json:"question_id"`
}

func (q *Queries) GetPlayerAnswerBySessionPlayerAndQuestion(ctx context.Context, arg GetPlayerAnswerBySessionPlayerAndQuestionParams) (PlayerAnswer, error) {
	row := q.db.QueryRow(ctx, getPlayerAnswerBySessionPlayerAndQuestion, arg.SessionPlayerID, arg.QuestionID)
	var i PlayerAnswer
	err := row.Scan(
		&i.ID,
		&i.SessionPlayerID,
		&i.QuestionID,
		&i.AnsweredAt,
		&i.IsCorrect,
		&i.Points,
	)
	return i, err
}

const getPlayerAnswersBySessionPlayer = `-- name: GetPlayerAnswersBySessionPlayer :many
SELECT pa.id, pa.session_player_id, pa.question_id, pa.answered_at, pa.is_correct, pa.points, q."order" AS question_order
FROM player_answers pa
JOIN questions q ON q.id = pa.question_id
WHERE pa.session_player_id = $1
ORDER BY q."order" ASC
`

type GetPlayerAnswersBySessionPlayerRow struct {
	ID              string             `json:"id"`
	SessionPlayerID string             `json:"session_player_id"`
	QuestionID      string             `json:"question_id"`
	AnsweredAt      pgtype.Timestamptz `json:"answered_at"`
	IsCorrect       bool               `json:"is_correct"`
	Points          int32              `json:"points"`
	QuestionOrder   int32              `json:"question_order"`
}

func (q *Queries) GetPlayerAnswersBySessionPlayer(ctx context.Context, sessionPlayerID string) ([]GetPlayerAnswersBySessionPlayerRow, error) {
	rows, err := q.db.Query(ctx, getPlayerAnswersBySessionPlayer, sessionPlayerID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []GetPlayerAnswersBySessionPlayerRow{}
	for rows.Next() {
		var i GetPlayerAnswersBySessionPlayerRow
		if err := rows.Scan(
			&i.ID,
			&i.SessionPlayerID,
			&i.QuestionID,
			&i.AnsweredAt,
			&i.IsCorrect,
			&i.Points,
			&i.QuestionOrder,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getSelectedAnswerIDs = `-- name: GetSelectedAnswerIDs :many
SELECT answer_id FROM player_answer_answers WHERE player_answer_id = $1
`

func (q *Queries) GetSelectedAnswerIDs(ctx context.Context, playerAnswerID string) ([]string, error) {
	rows, err := q.db.Query(ctx, getSelectedAnswerIDs, playerAnswerID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []string{}
	for rows.Next() {
		var answer_id string
		if err := rows.Scan(&answer_id); err != nil {
			return nil, err
		}
		items = append(items, answer_id)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getVotesForQuestion = `-- name: GetVotesForQuestion :many
SELECT paa.answer_id, COUNT(*) AS votes
FROM player_answer_answers paa
JOIN player_answers pa ON pa.id = paa.player_answer_id
JOIN session_players sp ON sp.id = pa.session_player_id
WHERE pa.question_id = $1 AND sp.session_id = $2
GROUP BY paa.answer_id
`

type GetVotesForQuestionParams struct {
	QuestionID string `json:"question_id"`
	SessionID  string `json:"session_id"`
}

type GetVotesForQuestionRow struct {
	AnswerID string `json:"answer_id"`
	Votes    int64  `json:"votes"`
}

func (q *Queries) GetVotesForQuestion(ctx context.Context, arg GetVotesForQuestionParams) ([]GetVotesForQuestionRow, error) {
	rows, err := q.db.Query(ctx, getVotesForQuestion, arg.QuestionID, arg.SessionID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []GetVotesForQuestionRow{}
	for rows.Next() {
		var i GetVotesForQuestionRow
		if err := rows.Scan(&i.AnswerID, &i.Votes); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
