// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: questions.sql

package db

import (
	"context"
)

const createQuestion = `-- name: CreateQuestion :one
INSERT INTO questions (id, quiz_id, text, image_url, type, "order", tags, time_limit, points)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9)
RETURNING id, quiz_id, text, image_url, type, "order", tags, time_limit, points
`

type CreateQuestionParams struct {
	ID        string       `json:"id"`
	QuizID    string       `json:"quiz_id"`
	Text      string       `json:"text"`
	ImageUrl  *string      `json:"image_url"`
	Type      QuestionType `json:"type"`
	Order     int32        `json:"order"`
	Tags      []string     `json:"tags"`
	TimeLimit int32        `json:"time_limit"`
	Points    int32        `json:"points"`
}

func (q *Queries) CreateQuestion(ctx context.Context, arg CreateQuestionParams) (Question, error) {
	row := q.db.QueryRow(ctx, createQuestion,
		arg.ID,
		arg.QuizID,
		arg.Text,
		arg.ImageUrl,
		arg.Type,
		arg.Order,
		arg.Tags,
		arg.TimeLimit,
		arg.Points,
	)
	var i Question
	err := row.Scan(
		&i.ID,
		&i.QuizID,
		&i.Text,
		&i.ImageUrl,
		&i.Type,
		&i.Order,
		&i.Tags,
		&i.TimeLimit,
		&i.Points,
	)
	return i, err
}

const deleteQuestion = `-- name: DeleteQuestion :exec
DELETE FROM questions WHERE id = $1
`

func (q *Queries) DeleteQuestion(ctx context.Context, id string) error {
	_, err := q.db.Exec(ctx, deleteQuestion, id)
	return err
}

const getQuestionByID = `-- name: GetQuestionByID :one
SELECT id, quiz_id, text, image_url, type, "order", tags, time_limit, points FROM questions WHERE id = $1
`

func (q *Queries) GetQuestionByID(ctx context.Context, id string) (Question, error) {
	row := q.db.QueryRow(ctx, getQuestionByID, id)
	var i Question
	err := row.Scan(
		&i.ID,
		&i.QuizID,
		&i.Text,
		&i.ImageUrl,
		&i.Type,
		&i.Order,
		&i.Tags,
		&i.TimeLimit,
		&i.Points,
	)
	return i, err
}

const getQuestionsByQuizID = `-- name: GetQuestionsByQuizID :many
SELECT id, quiz_id, text, image_url, type, "order", tags, time_limit, points FROM questions WHERE quiz_id = $1 ORDER BY "order" ASC
`

func (q *Queries) GetQuestionsByQuizID(ctx context.Context, quizID string) ([]Question, error) {
	rows, err := q.db.Query(ctx, getQuestionsByQuizID, quizID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Question{}
	for rows.Next() {
		var i Question
		if err := rows.Scan(
			&i.ID,
			&i.QuizID,
			&i.Text,
			&i.ImageUrl,
			&i.Type,
			&i.Order,
			&i.Tags,
			&i.TimeLimit,
			&i.Points,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateQuestion = `-- name: UpdateQuestion :one
UPDATE questions SET
    text       = $2,
    image_url  = $3,
    type       = $4,
    "order"    = $5,
    tags       = $6,
    time_limit = $7,
    points     = $8
WHERE id = $1
RETURNING id, quiz_id, text, image_url, type, "order", tags, time_limit, points
`

type UpdateQuestionParams struct {
	ID        string       `json:"id"`
	Text      string       `json:"text"`
	ImageUrl  *string      `json:"image_url"`
	Type      QuestionType `json:"type"`
	Order     int32        `json:"order"`
	Tags      []string     `json:"tags"`
	TimeLimit int32        `json:"time_limit"`
	Points    int32        `json:"points"`
}

func (q *Queries) UpdateQuestion(ctx context.Context, arg UpdateQuestionParams) (Question, error) {
	row := q.db.QueryRow(ctx, updateQuestion,
		arg.ID,
		arg.Text,
		arg.ImageUrl,
		arg.Type,
		arg.Order,
		arg.Tags,
		arg.TimeLimit,
		arg.Points,
	)
	var i Question
	err := row.Scan(
		&i.ID,
		&i.QuizID,
		&i.Text,
		&i.ImageUrl,
		&i.Type,
		&i.Order,
		&i.Tags,
		&i.TimeLimit,
		&i.Points,
	)
	return i, err
}
