// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: quizzes.sql

package db

import (
	"context"
)

const archiveQuiz = `-- name: ArchiveQuiz :exec
UPDATE quizzes SET archived = TRUE WHERE id = $1
`

func (q *Queries) ArchiveQuiz(ctx context.Context, id string) error {
	_, err := q.db.Exec(ctx, archiveQuiz, id)
	return err
}

const createQuiz = `-- name: CreateQuiz :one
INSERT INTO quizzes (id, title, description, category, time_per_question, points_per_question, scoring, difficulty, tags, cover_image_url, archived, author_id, created_at)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9, $10, FALSE, $11, NOW())
RETURNING id, title, description, category, time_per_question, points_per_question, scoring, difficulty, tags, cover_image_url, archived, author_id, created_at
`

type CreateQuizParams struct {
	ID                string   `json:"id"`
	Title             string   `json:"title"`
	Description       string   `json:"description"`
	Category          string   `json:"category"`
	TimePerQuestion   int32    `json:"time_per_question"`
	PointsPerQuestion int32    `json:"points_per_question"`
	Scoring           string   `json:"scoring"`
	Difficulty        string   `json:"difficulty"`
	Tags              []string `json:"tags"`
	CoverImageUrl     *string  `json:"cover_image_url"`
	AuthorID          string   `json:"author_id"`
}

func (q *Queries) CreateQuiz(ctx context.Context, arg CreateQuizParams) (Quiz, error) {
	row := q.db.QueryRow(ctx, createQuiz,
		arg.ID,
		arg.Title,
		arg.Description,
		arg.Category,
		arg.TimePerQuestion,
		arg.PointsPerQuestion,
		arg.Scoring,
		arg.Difficulty,
		arg.Tags,
		arg.CoverImageUrl,
		arg.AuthorID,
	)
	var i Quiz
	err := row.Scan(
		&i.ID,
		&i.Title,
		&i.Description,
		&i.Category,
		&i.TimePerQuestion,
		&i.PointsPerQuestion,
		&i.Scoring,
		&i.Difficulty,
		&i.Tags,
		&i.CoverImageUrl,
		&i.Archived,
		&i.AuthorID,
		&i.CreatedAt,
	)
	return i, err
}

const deleteQuiz = `-- name: DeleteQuiz :exec
DELETE FROM quizzes WHERE id = $1
`

func (q *Queries) DeleteQuiz(ctx context.Context, id string) error {
	_, err := q.db.Exec(ctx, deleteQuiz, id)
	return err
}

const getQuizByID = `-- name: GetQuizByID :one
SELECT id, title, description, category, time_per_question, points_per_question, scoring, difficulty, tags, cover_image_url, archived, author_id, created_at FROM quizzes WHERE id = $1
`

func (q *Queries) GetQuizByID(ctx context.Context, id string) (Quiz, error) {
	row := q.db.QueryRow(ctx, getQuizByID, id)
	var i Quiz
	err := row.Scan(
		&i.ID,
		&i.Title,
		&i.Description,
		&i.Category,
		&i.TimePerQuestion,
		&i.PointsPerQuestion,
		&i.Scoring,
		&i.Difficulty,
		&i.Tags,
		&i.CoverImageUrl,
		&i.Archived,
		&i.AuthorID,
		&i.CreatedAt,
	)
	return i, err
}

const listQuizzesByAuthor = `-- name: ListQuizzesByAuthor :many
SELECT id, title, description, category, time_per_question, points_per_question, scoring, difficulty, tags, cover_image_url, archived, author_id, created_at FROM quizzes
WHERE author_id = $1 AND archived = FALSE
ORDER BY created_at DESC
`

func (q *Queries) ListQuizzesByAuthor(ctx context.Context, authorID string) ([]Quiz, error) {
	rows, err := q.db.Query(ctx, listQuizzesByAuthor, authorID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Quiz{}
	for rows.Next() {
		var i Quiz
		if err := rows.Scan(
			&i.ID,
			&i.Title,
			&i.Description,
			&i.Category,
			&i.TimePerQuestion,
			&i.PointsPerQuestion,
			&i.Scoring,
			&i.Difficulty,
			&i.Tags,
			&i.CoverImageUrl,
			&i.Archived,
			&i.AuthorID,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateQuiz = `-- name: UpdateQuiz :one
UPDATE quizzes SET
    title               = $2,
    description         = $3,
    category            = $4,
    time_per_question   = $5,
    points_per_question = $6,
    scoring             = $7,
    difficulty          = $8,
    tags                = $9,
    cover_image_url     = $10
WHERE id = $1
RETURNING id, title, description, category, time_per_question, points_per_question, scoring, difficulty, tags, cover_image_url, archived, author_id, created_at
`

type UpdateQuizParams struct {
	ID                string   `json:"id"`
	Title             string   `json:"title"`
	Description       string   `json:"description"`
	Category          string   `json:"category"`
	TimePerQuestion   int32    `json:"time_per_question"`
	PointsPerQuestion int32    `json:"points_per_question"`
	Scoring           string   `json:"scoring"`
	Difficulty        string   `json:"difficulty"`
	Tags              []string `json:"tags"`
	CoverImageUrl     *string  `json:"cover_image_url"`
}

func (q *Queries) UpdateQuiz(ctx context.Context, arg UpdateQuizParams) (Quiz, error) {
	row := q.db.QueryRow(ctx, updateQuiz,
		arg.ID,
		arg.Title,
		arg.Description,
		arg.Category,
		arg.TimePerQuestion,
		arg.PointsPerQuestion,
		arg.Scoring,
		arg.Difficulty,
		arg.Tags,
		arg.CoverImageUrl,
	)
	var i Quiz
	err := row.Scan(
		&i.ID,
		&i.Title,
		&i.Description,
		&i.Category,
		&i.TimePerQuestion,
		&i.PointsPerQuestion,
		&i.Scoring,
		&i.Difficulty,
		&i.Tags,
		&i.CoverImageUrl,
		&i.Archived,
		&i.AuthorID,
		&i.CreatedAt,
	)
	return i, err
}
