// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: session_players.sql

package db

import (
	"context"
)

const createSessionPlayer = `-- name: CreateSessionPlayer :one
INSERT INTO session_players (id, session_id, user_id, score, joined_at)
VALUES ($1, $2, $3, 0, NOW())
RETURNING id, session_id, user_id, score, joined_at
`

type CreateSessionPlayerParams struct {
	ID        string `json:"id"`
	SessionID string `json:"session_id"`
	UserID    string `json:"user_id"`
}

func (q *Queries) CreateSessionPlayer(ctx context.Context, arg CreateSessionPlayerParams) (SessionPlayer, error) {
	row := q.db.QueryRow(ctx, createSessionPlayer, arg.ID, arg.SessionID, arg.UserID)
	var i SessionPlayer
	err := row.Scan(
		&i.ID,
		&i.SessionID,
		&i.UserID,
		&i.Score,
		&i.JoinedAt,
	)
	return i, err
}

const getLeaderboard = `-- name: GetLeaderboard :many
SELECT
    sp.id   AS session_player_id,
    sp.score,
    u.id    AS user_id,
    u.name
FROM session_players sp
JOIN users u ON u.id = sp.user_id
WHERE sp.session_id = $1
ORDER BY sp.score DESC
`

type GetLeaderboardRow struct {
	SessionPlayerID string `json:"session_player_id"`
	Score           int32  `json:"score"`
	UserID          string `json:"user_id"`
	Name            string `json:"name"`
}

func (q *Queries) GetLeaderboard(ctx context.Context, sessionID string) ([]GetLeaderboardRow, error) {
	rows, err := q.db.Query(ctx, getLeaderboard, sessionID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []GetLeaderboardRow{}
	for rows.Next() {
		var i GetLeaderboardRow
		if err := rows.Scan(
			&i.SessionPlayerID,
			&i.Score,
			&i.UserID,
			&i.Name,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getSessionPlayerByID = `-- name: GetSessionPlayerByID :one
SELECT id, session_id, user_id, score, joined_at FROM session_players WHERE id = $1
`

func (q *Queries) GetSessionPlayerByID(ctx context.Context, id string) (SessionPlayer, error) {
	row := q.db.QueryRow(ctx, getSessionPlayerByID, id)
	var i SessionPlayer
	err := row.Scan(
		&i.ID,
		&i.SessionID,
		&i.UserID,
		&i.Score,
		&i.JoinedAt,
	)
	return i, err
}

const getSessionPlayerByUserAndSession = `-- name: GetSessionPlayerByUserAndSession :one
SELECT id, session_id, user_id, score, joined_at FROM session_players WHERE session_id = $1 AND user_id = $2
`

type GetSessionPlayerByUserAndSessionParams struct {
	SessionID string `json:"session_id"`
	UserID    string `json:"user_id"`
}

func (q *Queries) GetSessionPlayerByUserAndSession(ctx context.Context, arg GetSessionPlayerByUserAndSessionParams) (SessionPlayer, error) {
	row := q.db.QueryRow(ctx, getSessionPlayerByUserAndSession, arg.SessionID, arg.UserID)
	var i SessionPlayer
	err := row.Scan(
		&i.ID,
		&i.SessionID,
		&i.UserID,
		&i.Score,
		&i.JoinedAt,
	)
	return i, err
}

const getSessionPlayers = `-- name: GetSessionPlayers :many
SELECT id, session_id, user_id, score, joined_at FROM session_players WHERE session_id = $1
`

func (q *Queries) GetSessionPlayers(ctx context.Context, sessionID string) ([]SessionPlayer, error) {
	rows, err := q.db.Query(ctx, getSessionPlayers, sessionID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []SessionPlayer{}
	for rows.Next() {
		var i SessionPlayer
		if err := rows.Scan(
			&i.ID,
			&i.SessionID,
			&i.UserID,
			&i.Score,
			&i.JoinedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const incrementPlayerScore = `-- name: IncrementPlayerScore :one
UPDATE session_players SET score = score + $2 WHERE id = $1 RETURNING id, session_id, user_id, score, joined_at
`

type IncrementPlayerScoreParams struct {
	ID    string `json:"id"`
	Score int32  `json:"score"`
}

func (q *Queries) IncrementPlayerScore(ctx context.Context, arg IncrementPlayerScoreParams) (SessionPlayer, error) {
	row := q.db.QueryRow(ctx, incrementPlayerScore, arg.ID, arg.Score)
	var i SessionPlayer
	err := row.Scan(
		&i.ID,
		&i.SessionID,
		&i.UserID,
		&i.Score,
		&i.JoinedAt,
	)
	return i, err
}
