// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: sessions.sql

package db

import (
	"context"
)

const createSession = `-- name: CreateSession :one
INSERT INTO quiz_sessions (id, quiz_id, room_code, status, created_at)
VALUES ($1, $2, $3, 'WAITING', NOW())
RETURNING id, quiz_id, room_code, status, started_at, created_at
`

type CreateSessionParams struct {
	ID       string `json:"id"`
	QuizID   string `json:"quiz_id"`
	RoomCode string `json:"room_code"`
}

func (q *Queries) CreateSession(ctx context.Context, arg CreateSessionParams) (QuizSession, error) {
	row := q.db.QueryRow(ctx, createSession, arg.ID, arg.QuizID, arg.RoomCode)
	var i QuizSession
	err := row.Scan(
		&i.ID,
		&i.QuizID,
		&i.RoomCode,
		&i.Status,
		&i.StartedAt,
		&i.CreatedAt,
	)
	return i, err
}

const deleteSession = `-- name: DeleteSession :exec
DELETE FROM quiz_sessions WHERE id = $1
`

func (q *Queries) DeleteSession(ctx context.Context, id string) error {
	_, err := q.db.Exec(ctx, deleteSession, id)
	return err
}

const finishSession = `-- name: FinishSession :exec
UPDATE quiz_sessions SET status = 'FINISHED' WHERE id = $1
`

func (q *Queries) FinishSession(ctx context.Context, id string) error {
	_, err := q.db.Exec(ctx, finishSession, id)
	return err
}

const getLatestSessionByQuizID = `-- name: GetLatestSessionByQuizID :one
SELECT id, quiz_id, room_code, status, started_at, created_at FROM quiz_sessions
WHERE quiz_id = $1
ORDER BY created_at DESC
LIMIT 1
`

func (q *Queries) GetLatestSessionByQuizID(ctx context.Context, quizID string) (QuizSession, error) {
	row := q.db.QueryRow(ctx, getLatestSessionByQuizID, quizID)
	var i QuizSession
	err := row.Scan(
		&i.ID,
		&i.QuizID,
		&i.RoomCode,
		&i.Status,
		&i.StartedAt,
		&i.CreatedAt,
	)
	return i, err
}

const getSessionByID = `-- name: GetSessionByID :one
SELECT id, quiz_id, room_code, status, started_at, created_at FROM quiz_sessions WHERE id = $1
`

func (q *Queries) GetSessionByID(ctx context.Context, id string) (QuizSession, error) {
	row := q.db.QueryRow(ctx, getSessionByID, id)
	var i QuizSession
	err := row.Scan(
		&i.ID,
		&i.QuizID,
		&i.RoomCode,
		&i.Status,
		&i.StartedAt,
		&i.CreatedAt,
	)
	return i, err
}

const getSessionByRoomCode = `-- name: GetSessionByRoomCode :one
SELECT id, quiz_id, room_code, status, started_at, created_at FROM quiz_sessions WHERE room_code = $1
`

func (q *Queries) GetSessionByRoomCode(ctx context.Context, roomCode string) (QuizSession, error) {
	row := q.db.QueryRow(ctx, getSessionByRoomCode, roomCode)
	var i QuizSession
	err := row.Scan(
		&i.ID,
		&i.QuizID,
		&i.RoomCode,
		&i.Status,
		&i.StartedAt,
		&i.CreatedAt,
	)
	return i, err
}

const startSession = `-- name: StartSession :one
UPDATE quiz_sessions SET status = 'ACTIVE', started_at = NOW() WHERE id = $1 RETURNING id, quiz_id, room_code, status, started_at, created_at
`

func (q *Queries) StartSession(ctx context.Context, id string) (QuizSession, error) {
	row := q.db.QueryRow(ctx, startSession, id)
	var i QuizSession
	err := row.Scan(
		&i.ID,
		&i.QuizID,
		&i.RoomCode,
		&i.Status,
		&i.StartedAt,
		&i.CreatedAt,
	)
	return i, err
}

const updateSessionStatus = `-- name: UpdateSessionStatus :one
UPDATE quiz_sessions SET status = $2 WHERE id = $1 RETURNING id, quiz_id, room_code, status, started_at, created_at
`

type UpdateSessionStatusParams struct {
	ID     string        `json:"id"`
	Status SessionStatus `json:"status"`
}

func (q *Queries) UpdateSessionStatus(ctx context.Context, arg UpdateSessionStatusParams) (QuizSession, error) {
	row := q.db.QueryRow(ctx, updateSessionStatus, arg.ID, arg.Status)
	var i QuizSession
	err := row.Scan(
		&i.ID,
		&i.QuizID,
		&i.RoomCode,
		&i.Status,
		&i.StartedAt,
		&i.CreatedAt,
	)
	return i, err
}
